### ISSUE TITLE
Append functionality dbWriteTable

### ISSUE THREAD

**Issue by jjuppe** [s-u/RJDBC#85] opened 2021-01-15 13:06 UTC
Hi,

I created a table "test_table" with the following statement:
`dbWriteTable(con_jdbc, "test_table", df)`

Next, I would like to append the same dataframe to the exact same table:
`dbWriteTable(con_jdbc, "test_table", df, append=T, row.names=F, overwrite=F)`
 but this yields the error message: Cannot append to a non-existing table `test_table'. 

However, that table should exist based upon previous statement. 
Can somebody please support?

Thank you, Janis

**Comment by s-u** [comment] 2021-03-16 21:32
Please provide full details: full output from the R session (code executed and all output), sessionInfo(), details about your DBMA (database software), JDBC driver, JDK/JRE. You say it "should" exist, but does it? Have you checked your DBMA?

**Comment by s-u** [comment] 2021-03-17 21:53
Since this is not reproducible in the DBMAs we test (MySQL, SQLite) I'll close this. Please re-open with more details if it is still relevant.

**Closed by s-u** 2021-03-17 21:53 UTC
