### ISSUE TITLE
Errors in ShinyApp inside reactive on Ubuntu but not Windows

### ISSUE THREAD

**Issue by MikeJansen** [s-u/RJDBC#93] opened 2022-06-27 15:52 UTC
We are using R Shiny Apps and RJDBC connections to Vertica.  On Ubuntu we are finding that in larger apps that JDBC seems to get messed up.  It seems this only occurs if there is more than reactive()  that includes a dbGetQuery() being executed fresh (not returning cached results) during a UI rendering.  For example, a tab that has only one dbGetQuery getting executed works, but a tab with two does not work.

The error on the dbGetQuery is:

`Warning: Error in .jcheck: Java Exception <no description because toString() failed>.jcall(conn@jc, "Ljava/sql/Statement;", "createStatement")new("jobjRef", jobj = <pointer: 0x55dc8786b878>, jclass = "java/lang/Throwable")`

I cannot find any way to get better logging output to get more details on the error.  I have stepped into the code with RStudio on Ubuntu.  It seems that at the point where the error occurs, if I am debugging, any JDBC call (such as a connect) will error as well.

Are there any known issues on Ubuntu using RJDBC in a Shiny App ?

More details:

JDBC init code, has been placed globally, in server function, and in reactive(), with no change (except change in error message to be on the connection when its in the reactive():

```
vDriver <- JDBC(driverClass = "com.vertica.jdbc.Driver",
                classPath = "./vertica-jdbc-10.0.0-0.jar")
vertica <- dbConnect(vDriver, "jdbc:vertica://X.X.X.X:5433/vertica-db","user", "pwd")

```

Call that can fail (similar).  Fails at the `dbGetQuery`, or any JDBC call at that point (I've tried connects inside the debugger here):
```
reactive_data <- reactive({
  loginfo("user_data:actual_installs REACTIVE\n")
  install_data<-dbGetQuery(vertica, actual_installs_sql)
  loginfo("query done")
  install_data<-as.data.frame(install_data)
  return(install_data)
})
```

The reactive's get executed in the context of rendering a `fluidPage`.

A very simple example works.  The failure seems to happen in more complex apps when there is more than one reactive calling a `dbGetQuery` during a server call (e.g. a tab with two plots that get rendered).

The actual apps use many other packages (sqldf, etc.) to process the `dbGetQuery` results before rendering, but the error is occurring up front at the `dbGetQuery` call.

**Comment by s-u** [comment] 2022-06-27 20:38
Can you include minimal example? How are you running the Shiny app? If Shiny is using `fork()` on unix in your app then you need to make sure that you do not initialize Java before the `fork()` since JVM is not fork-safe. That's the only thing I can think of on top of my head without an actual example.

**Comment by souradippal** [comment] 2022-08-25 21:40
@s-u Hello Simon, I am also getting Same error, I am getting almost crazy to debug this issue. The issue is not happening on my windows laptop. But it is happening when I am trying to run the app on the RStudio connect server. We dont have admin rights on the server, so I am not sure, how we can stop initialize java before the application start. This is the trace which I got. I am trying to generate a xlsx file with many tabs inside a Shiny downloadHandler. I am getting data from the database using RJDBC inside downloadHandler. I would really thankful, if could help me in this. Thanks a lot in advance.

08/25 21:26:54.564 (GMT)
Warning: Error in .jcheck: Java Exception <no description because toString() failed>.jcall(conn@jc, "Ljava/sql/Statement;", "createStatement")new("jobjRef", jobj = <pointer: 0x122fca08>, jclass = "java/lang/Throwable")
08/25 21:26:54.570 (GMT)
15: <Anonymous>
08/25 21:26:54.570 (GMT)
13: fn
08/25 21:26:54.570 (GMT)
8: retry
08/25 21:26:54.570 (GMT)
7: connect$retryingStartServer
08/25 21:26:54.570 (GMT)
6: eval
08/25 21:26:54.570 (GMT)
5: eval
08/25 21:26:54.570 (GMT)
4: eval
08/25 21:26:54.570 (GMT)
3: eval
08/25 21:26:54.570 (GMT)
2: eval.parent
08/25 21:26:54.571 (GMT)
1: local

**Comment by s-u** [comment] 2022-08-26 03:45
I would ask RStudio for support. As noted above, you cannot fork RJDBC so if it doubt (I don't know if RStudio uses `fork` or not - but Windows doesn't support `fork` so that could be an indication), put all RJDBC code into the reactive part an NOT into the server part.

**Comment by souradippal** [comment] 2022-08-26 14:30
Hello @s-u, Thanks for the suggestion, I tried to put everything in the reactive part. But without any luck. Do you have any other suggestions?

**Comment by s-u** [comment] 2022-12-23 03:08
I'll close this as not reproducible due to lack of details. At the very least we need some reproducible code to look into it.

**Closed by s-u** 2022-12-23 03:08 UTC
