### ISSUE TITLE
Issue using dbWritetable for dataframe with NULL columns

### ISSUE THREAD

**Issue by ghareesh** [s-u/RJDBC#82] opened 2020-05-17 18:35 UTC
Hi Team..
Using the below code snippet to create table in HANA..

if (dbExistsTable(jdbcConnection_sap, "TEST_ML")) {dbRemoveTable(jdbcConnection_sap, "TEST_ML")}
dbWriteTable(
  jdbcConnection_sap,
  "TEST_ML",
  dataframe_to_be_written_to_hana,
  field.types = NULL,
  overwrite = TRUE
)

Error in .local(conn, statement, ...) : 
  execute JDBC update query failed in dbSendUpdate ([307]: numeric value out of range: nan: type_code=7, index=1(input position 25))

The dataframe_to_be_written_to_hana has lot of NA values.. and some columns are full NAs.. Thats how the data is unfortunately.. 

Is there a way to have this fixed please? Also how can I specify non-default schemas in dbWritetable?

**Comment by s-u** [comment] 2021-03-18 01:53
This is likely a duplicate of #63 and should be addressed by #78

Note that `dbWriteTable` is only a convenience wrapper for `dbSendUpdate(c, "CREATE TABLE ...")` and `dbSendUpdate(c, "INSERT INTO ...", list=data))` for very simple tables so you may want to use those directly if you have anything beyond trivial tables.

**Closed by s-u** 2021-03-18 01:53 UTC
