### ISSUE TITLE
dbGetQuery generates out of heap memory when using PostgreSQL

### ISSUE THREAD

**Issue by schuemie** [s-u/RJDBC#15] opened 2015-01-05 02:49 UTC
The problem is caused by PostgreSQL ignoring the `ResultSet.setFetchSize()` call. To prevent Postgres from caching all results locally, you'd need to do two things:
1. Turn off autocommit before creating the statement:
   
   ``` r
   .jcall(connection@jc,"V",method="setAutoCommit",FALSE)
   ```
   
   and don't forget to turn it back on:
   
   ``` r
   on.exit(.jcall(connection@jc,"V",method="setAutoCommit",TRUE), add = TRUE)
   ```
2. Call setFetchSize on the Statement object:
   
   ``` r
   .jcall(s,"V",method="setFetchSize",as.integer(2048L))
   ```

**Comment by s-u** [comment] 2015-01-05 03:23
This seems like a bug in the driver (assuming your analysis is correct) - the point of DBIs is that you fetch results explicitly, not that you load it all into memory. In fact, the usual default is the inverse - don't fetch anything until explicitly requested - that's why `setFetchSize` was designed to serve exactly the opposite purpose - to tell the driver that it's ok to read more than a handful of rows. I fear there is nothing RDBC can do about bad drivers. That said, if there is actually something wrong with RDJBC, I'd like to know.

**Comment by schuemie** [comment] 2015-01-05 06:26
I can confirm that the changes I mentioned do prevent the out-of-heap-memory, we currently using them in an adapted version of RJDBC's dbGetQuery function.

Even though the behavior is inconsistent with other drivers (we're also running Oracle and SQL Server which don't behave like this), the Postgres folks certainly don't seem to think there is something wrong with their driver, since this is documented behavior:
http://jdbc.postgresql.org/documentation/83/query.html#query-with-cursor

**Comment by s-u** [comment] 2015-01-05 07:20
Well, from that link it seems that cursor-based access is merely an afterthought in their database which is probably why they go into such lengths to disable it. That doesn't change the fact that they are the odd ones out abusing fetch size hint to enable something that's natural to other databases. Since RJDBC is a cross-platform interface, it's not our place to work around issues in specific database drivers - in particular when they are using it in a manner in consistent with everyone else. If it was just a matter of let's say disabling auto-commit then I could envision simply providing that feature and have users that really want to use Postgres to deal with the broken model. Hoever, since it seems they require fetch size at the statement level, that is entirely unrealistic, because that's before any decision on fetching has been made.

So unless anyone has a better idea, I'll just close this as documentation item, so people that have no choice but to use Postgress for large result sets will have a way to work around the limitations of the Postgress drivers when they need to.

**Comment by schuemie** [comment] 2015-01-05 08:15
The other platforms do not mind having the setFetchSize on the Statement object (we use the same code for all platforms). I guess it's just different interpretations of the JDBC standard.

It would really just be a few lines of code that fixes the issue for Postgres, but doesn't break anything for any other platform. I would argue it improves cross-platform compatibility.

FYI: the same drivers are also used by Amazon Redshift, who's users would also not be able to use RJDBC without these changes.

**Comment by s-u** [comment] 2015-01-05 16:22
It doesn't fix the issue - it adds a very bad hack - you're hard-coding a hint with a random number before any fetch is in place. Like I said, if you have an actual solution, I would be happy to integrate it, but not a random hack.

**Comment by schuemie** [comment] 2015-01-06 01:31
Ok, I'll stop bothering you. But one last question because this truly puzzles me: if the setFetchSize() on the Statement object is a very bad hack, then why is it in the JDBC standard?

**Comment by s-u** [comment] 2015-01-06 02:22
The main problem is that it's an unsolicited change entirely out of the blue. The fetch size is governed by the `fetch()` function which makes sense since that is when the user code decides how to fetch the result - whether en-block or piecewise. The problem with the above is that it requires some assumption before the statement is even executed at which point RJDBC has no knowledge as of how the result will be used. The paradoxical part is that the driver abuses `setFetchSize` for the inverse function - the default fetch size is 10 which should really be a hint to the driver that it shouldn't load everything in memory, but the driver decides to do the exact opposite - I have no idea why - it certainly doesn't make any sense.

I was re-reading the standard, and the only work-around I can think of would be to have some API to attempt to check the result type which is available from the statement and provide some options to try to influence it. The R API doesn't actually provide objects for statements, so I'm not quite sure how this would even look at the design stage - the best I can think of would be some hint at the `dbSendQuery` stage. To make things worse, there is not even a standard for actually influencing the result set type in JDBC, so this is really a long shot that would require some design and testing with various drivers...

**Comment by schuemie** [comment] 2015-01-08 07:59
Happy to help with the testing. 

I'm not sure I understand all you're saying. Right now, you're setting the fetch size on the ResultSet on line 73 [here](https://github.com/s-u/RJDBC/blob/master/java/JDBCResultPull.java), which comes from the `fetchSize` parameter which is in R the `block` parameter, which gets the default value 2048 on line 287 [here](https://github.com/s-u/RJDBC/blob/master/R/class.R). The block parameter is invisible to users of `dbGetQuery()`.

One way to go about it would be that users of the `dbGetQuery()` function have an explicit parameter `fetchSize` (with default value 2048), which is passed to both the `dbSendQuery()` function where it can be passed to the Java Statement object, and to the `fetch()` function where it can be passed to the ResultSet object like it is right now. But I guess I'm missing something.

For me the weird part is that the JDBC part allows two places to set the fetch size. I don't see a very elegant way of hiding that in RJDBC.

**Comment by vlsi** [comment] 2018-01-09 18:09
Just in case someone would find this issue:

1) pgjdbc does support default fetchsize since 9.4-1202 (see https://github.com/pgjdbc/pgjdbc/pull/287 , https://jdbc.postgresql.org/documentation/changelog.html#version_9.4-1202 )
2) In order to fetch resultset in chunks in pgjdbc, you need to use non-zero fetchsize and `setAutoCommit(false)` (see https://www.slideshare.net/VladimirSitnikv/postgresql-and-jdbc-striving-for-high-performance slides 40-41)

>but the driver decides to do the exact opposite - I have no idea why - it certainly doesn't make any sense.

@s-u , "resultsets" vanish in PostgreSQL on commit (that is you cannot fetch across commit). AFAIK, that is a limitation of PostgreSQL wire protocol. That is why pgjdbc does eager fetch in `autocommit` mode.

**Comment by s-u** [comment] 2021-03-18 02:55
This has been a while, but in theory this may now work by using `dbBegin()` which disables auto-commit and perhaps `dbRollback()`. I'm still not clear if that is sufficient, or we need to worry about `fetchSize`. The `block=` argument is now present in `dbGetQuery` so it's in theory available, but as often with JDBC change for one database kills another five, so whether to pass it to the statement or not it still unclear.

**Comment by s-u** [comment] 2022-03-24 11:17
No more comments so assuming this is not an issue anymore.

**Closed by s-u** 2022-03-24 11:17 UTC
