### ISSUE TITLE
Issue with NA values

### ISSUE THREAD

**Issue by harveyl888** [s-u/RJDBC#63] opened 2018-07-30 16:29 UTC
I'm having an issue in using dbWriteTable with data frames that contain NA values.

```r
library(DBI)
library(RJDBC)

# drv <-  ...
# db <- dbConnect ...   ## connect to database

dbExecute(db, "CREATE TABLE test01
           (
           name VARCHAR(50),
           value FLOAT
           )")

df1 <- data.frame(name = c('A1', 'B1', 'C1'), value = c(1.1, 2.2, 3.3), stringsAsFactors = FALSE)
df2 <- data.frame(name = c('A2', 'B2', 'C2'), value = c(NA, 2.2, 3.3), stringsAsFactors = FALSE)
df3 <- data.frame(name = c('A3', 'B3', 'C3'), value = c(1.1, NA, 3.3), stringsAsFactors = FALSE)

dbWriteTable(db, 'test01', df1, overwrite = FALSE, append = TRUE)
dbWriteTable(db, 'test01', df2, overwrite = FALSE, append = TRUE)
dbWriteTable(db, 'test01', df3, overwrite = FALSE, append = TRUE)

dbDisconnect(db)
```

When running `dbWriteTable` on a table containing NA I get the following error:

**Error in .local(conn, statement, ...) : 
  execute JDBC update query failed in dbSendUpdate (The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 2 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision.)**

The resulting table in the database looks like this:

| name | value |
| --- | --- |
| A1 | 1.1 |
| B1 | 2.2 |
| C1 | 3.3 |
| B2 | 2.2 |
| C2 | 3.3 |

This occurs when running RJDBC version 0.2-7.1, DBI version 1.0.0.

Rolling back to RJDBC version 0.2-5 produces the desired output:

| name | value |
| --- | --- |
| A1 | 1.1 |
| B1 | 2.2 |
| C1 | 3.3 |
| A2 | NA |
| B2 | 2.2 |
| C2 | 3.3 |
| A3 | 1.1 |
| B3 | NA |
| C3 | 3.3 |

**Comment by gmeroni** [comment] 2018-07-31 09:08
Got the same issue but unfortunately the downgrade of the version could not be a valid solution due to the increase of computational times.

```
##8550 rows and 56 columns
0.2-7 → 0.9''
0.2-5 → 39''
```

**Comment by dernst** [comment] 2018-07-31 15:07
Numeric values in R are double precision floating point values (usually 64-bit) and you seem to be trying to insert these into a single-precision floating point column. Since `RJDBC` currently does not handle missing values it tries to insert a double-precision NaN value which is outside the range of the single precision column. You could try to instead create the column as `double` in SQL.

Generally `RJDBC` should IMO insert NULL instead for missing values. You can try if installing the package from this repo alleviates your problems: https://github.com/dernst/RJDBC . You'd have to manually compile the Java code before `R CMD INSTALL` like so:
```
mkdir -p inst/java
javac -d inst/java java/*.java
(cd inst/java; jar fvc RJDBC.jar info; rm -rf info)
```

**Comment by bruckerflo** [comment] 2018-09-06 13:38
I have the same issue and creating the column as double in SQL doesn't do the trick because SQL is using float(53) by default anyway. Having no clue about Java, I'm kind of stuck here too.

**Comment by dernst** [comment] 2018-09-07 08:08
@bruckerflo which database are you using? `DOUBLE PRECISION` should be equivalent to `FLOAT(53)` in sql server though I have no experience with sql server and haven't tested that.

**Comment by dernst** [comment] 2018-09-07 13:09
Have you tried my changes above yet? 
Maybe `odbc` (https://github.com/r-dbi/odbc) is of help as well. This link has some information too: https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/using-integrated-authentication?view=sql-server-2017 . It seems possible but I can't be of help here unfortunately.

**Comment by CerebralMastication** [comment] 2018-09-14 17:32
> I'm using MS SQL Server 2016 but I had the same issue with earlier versions before. It just didn't bother me back then because I was working under Windows where I could easily switch to RODBC. But now I'm working with the RStudio Server Pro on Linux and so it became quite hard to connect to our MS SQL databases which are using a trusted connection... RJDBC offers this out of the box but apparently only for tables without missing values...

I'm having the same problem for the same reason. Only I'm on Mac. But can't use odbc because none of the MSFT odbc drivers support the right authentication on Mac/Linux. Even the MSFT odbc driver for linux does not support "windows authentication" on Linux.  Only the JDBC drivers seems to work... but the lack of being able to write is a hard constraint.

**Comment by smoens** [comment] 2018-11-21 10:20
For me this was caused by divisions by 0. If there is a division by 0 the value "**Inf**" was returned in my data.frame. I solved this with an ifelse-statement substituting "Inf" with NA which solved the issue.

**Comment by OlliSagi** [comment] 2019-01-14 11:39
Hi all,

The problem occurs because there are three (maybe more) different values in R for values that are not concretely defined. It's either "Inf" , "NaN" or "NA". Now dbWriteTable can handle NA by converting these to "NULL" when moving it to SQL. However "NaN" and "Inf" are not recognized thus giving the "Check the source data for invalid values" error. The fix is as following:

Suppose this is your table that you want to write to SQL:

Tablename: "df"
USER quality
1       Inf
2       NaN
3       0.3

The first thing you want to do is convert all "NaN" to "NA" because dbWriteTable can recognize these. This can be done simply by:

df[is.na(df)] <- NA

Then you still have your "Inf" values. Unfortunately I haven't found a easy way to go through the entire table in one line. But check which columns have "Inf" and do them one by one as following:

df$quality[is.nan(df$quality)] <- NA

If your table is cleaned up it shouldn't give these errors. Here is another example of how to use dbWriteTable just to make things more clear:

dbWriteTable(ODBCconnectionname, DBMStablename, YourRtablename,
             field.types = c(USER="integer",
                             quality="float(53)",
                             ))

Check which data types you need on this page:
https://www.w3schools.com/sql/sql_datatypes.asp

If you need more info just PM me.

**Comment by dernst** [comment] 2019-01-14 13:58
@OlliSagi 
That would still require that the backend dbi package handle `NA` values. As you mentioned `odbc` implements this correctly AFAICT but `RJDBC` does not.
btw you can use `is.finite` to test for Inf and -Inf

**Comment by s-u** [comment] 2021-03-18 02:15
This should now work:

```
> dbReadTable(db, 'test01')
  name value
1   A1   1.1
2   B1   2.2
3   C1   3.3
4   A2    NA
5   B2   2.2
6   C2   3.3
7   A3   1.1
8   B3    NA
9   C3   3.3
```

**Closed by s-u** 2021-03-18 02:15 UTC
