### ISSUE TITLE
JDBC() with Teradata driver failing to load tdgssconfig.jar

### ISSUE THREAD

**Issue by m-stanley** [s-u/RJDBC#35] opened 2016-02-19 15:43 UTC
Using JDBC() with two .jars in the ClassPath seems to be failing to load one of the .jar files. The Teradata driver includes two .jar files (I don't think the license allows me to attach them, but it's available online [here](https://downloads.teradata.com/download/connectivity/jdbc-driver)) and if I run `JDBC(driverClass = "com.teradata.jdbc.TeraDriver", classPath = "C:\\terajdbc4.jar;C:\\tdgssconfig.jar")` the resulting driver fails to load tdgssconfig.jar properly. Trying to use it throws an error:

```
> drv <- JDBC("com.teradata.jdbc.TeraDriver", "C:\\tdgssconfig.jar;C:\\terajdbc4.jar", identifier.quote = "\"") 
> conn  <- dbConnect(drv, "jdbc:teradata://hostname/")
Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  : 
  java.lang.NoClassDefFoundError: Could not initialize class com.teradata.tdgss.jtdgss.TdgssManager
```

This is the error that's thrown when tdgssconfig.jar isn't on the ClassPath or isn't loaded properly. Hopefully it's as simple as that to reproduce the error.

To fix the error, I modified `JDBC()` to use .jpackage to load the package .jar and then .jaddClassPath to add each specified .jar to the class path individually, and this seemed to resolve it. The existing version uses .jinit to add the specified packages and then .jaddClassPath to add the package's .jar, but I don't know enough Java to know why that would fix it.

I noticed that the rJava documentation for .jinit says "Starting with version 0.5 rJava provides a custom class laoder that can automatically track classes and native libraries that are provided in R packages. Therefore R packages should NOT use .jinit, but call .jpackage instead. In addition this allows the use of class path modifying function .jaddClassPath." so that's the reason I swapped to .jpackage. Perhaps the use of .jinit in this package was preventing the use of .jaddClassPath to add .jars.

Here's my working example:

```
JDBC <- function(driverClass='', classPath=NA, identifier.quote=NA) {
  .jpackage("RJDBC", jars = "RJDBC.jar")
  if (!is.na(classPath[1])) {
    classPath <- path.expand(unlist(strsplit(classPath, .Platform$path.sep)))
    sapply(classPath, .jaddClassPath)
    }
  if (nchar(driverClass) && is.jnull(.jfindClass(as.character(driverClass)[1])))
    stop("Cannot find JDBC driver class ",driverClass)
  jdrv <- .jnew(driverClass, check=FALSE)
  .jcheck(TRUE)
  if (is.jnull(jdrv)) jdrv <- .jnull()
  new("JDBCDriver", identifier.quote=as.character(identifier.quote), jdrv=jdrv)
}
```

Thanks.

**Comment by jmorten** [comment] 2016-12-09 22:46
Here is what i do

```r
library(RJDBC)
library(DBI)
library(rJava)

JAR_DIR <- "path/to/drivers/"
drv <- try(JDBC("com.teradata.jdbc.TeraDriver", paste0(JAR_DIR, 'terajdbc4.jar')))
.jaddClassPath(paste(JAR_DIR, "terajdbc4.jar", sep=""))
.jaddClassPath(paste(JAR_DIR, "tdgssconfig.jar", sep=""))
drv <- JDBC(driverClass="com.teradata.jdbc.TeraDriver")
databse <- dbConnect(drv,"jdbc:teradata://hostname/TMODE=ANSI,charset=UTF8,USER=user,PASSWORD=password")
```

**Comment by mkorvink** [comment] 2019-03-05 13:54
I had this issue and it was resolved by reinstalling the RJDBC package from CRAN.

I'm connecting the following way (Mac OS): 

  drv <- RJDBC::JDBC(driverClass = "com.teradata.jdbc.TeraDriver", classPath = "<path>/terajdbc4.jar;<path>/tdgssconfig.jar")
  conn <- dbConnect(drv,'jdbc:teradata://<server>/<db>',"username","password")
  return(dbGetQuery("select count(*) from table", sql))

**Comment by mc51** [comment] 2019-03-18 10:26
This seems to be a bug, because I had the same issue.
It was especially strange because it used to work before, i.e. the first time I tried. Then, when reloading the driver for the first time it stopped working. I didn't make any changes in the meantime. 
Regarding the setup everything was correct in my case. The tdgssconfig.jar was referenced correctly and accessible. I also tried @mkorvink 's sugesstion to reinstall RJDBC, tried the latest Teradata JDBC drivers etc.  What helped was @jmorten's procedure!
I used to load the driver like this:

require(RJDBC)
drv <- JDBC("com.teradata.jdbc.TeraDriver",
            "C:\\Users\\ME\\Software\\tera\\terajdbc4.jar;C:\\Users\\ME\\Software\\tera\\\tdgssconfig.jar")

Then, I checked if CLASSPATH was set correctly and it was not (tdgssconfig.jar is missing):
> print(.jclassPath())
[1] "C:\\Users\\ME\\Software\\Anaconda3\\Lib\\R\\library\\rJava\\java"           
[2] "C:\\Users\\ME\\Software\\Anaconda3\\Lib\\R\\library\\RJDBC\\java\\RJDBC.jar"
[3] "C:\\Users\\ME\\Software\\tera\\terajdbc4.jar" 

Now, this is what I did to fix it (Basically, the same that @jmorten suggested):

drv <- JDBC("com.teradata.jdbc.TeraDriver",
           "C:\\Users\\ME\\Software\\tera\\terajdbc4.jar;C:\\Users\\ME\\Software\\tera\\\tdgssconfig.jar")
.jaddClassPath(C:\\Users\\ME\\Software\\tera\\\tdgssconfig.jar)

Result:
> print(.jclassPath())
[1] "C:\\Users\\ME\\Software\\Anaconda3\\Lib\\R\\library\\rJava\\java"           
[2] "C:\\Users\\ME\\Software\\Anaconda3\\Lib\\R\\library\\RJDBC\\java\\RJDBC.jar"
[3] "C:\\Users\\ME\\Software\\tera\\terajdbc4.jar"                               
[4] "C:\\Users\\ME\\Software\\tera\\tdgssconfig.jar"  

--> Now, i can connect


Here is my Setup: 
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RJDBC_0.2-7.1        rJava_0.9-10         DBI_1.0.0            RevoUtils_11.0.1     RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
[1] compiler_3.5.1

**Comment by dernst** [comment] 2019-03-18 13:21
@mc51 I can't find a case where adding two jar files to the class path either via `.jinit` or `JDBC` would not work. Unfortunately rJava fails silently if it cannot find the jar files.

Can you try the following:
```
# before loading rJava/RJDBC:
options(java.parameters="-DrJava.debug=1")
# insert correct paths here
drv <- JDBC("com.teradata.jdbc.TeraDriver", "path/to/terajdbc4.jar;path/to/tdgssconfig.jar")
print(.jclassPath())
```
which should produce significantly more output, which you can post here as a *code block* (so github doesn't mangle the output) with triple backticks (```).

**Comment by s-u** [comment] 2019-03-18 14:26
@mc51 please note that strings like "C:\Users\ME\Software\tera\terajdbc4.jar" are invalid, you have to use "\\" to quote backslashes.
@dernts yes, good call, debugging ususally helps. Note that in a running rJava session you can also use `.jclassLoader()$setDebug(1L)`

**Comment by mc51** [comment] 2019-03-19 08:09
@s-u You're right. But my actual code is using \\. I think it's just a display issue here?  Anyways, like I said before I'm very confident the setup was correct. It was not an issue of invalid paths. 

@dernst: Now, it getting strange again. After restarting and trying your suggestion the issue seems to disappear. Like I said before, the issue is rather unpredictable. Everything used to be fine for quite some time and then it suddenly appeared. Maybe it is related to Jupyter-lab or DBeaver which is use in parallel. I'll be on the lookout for any patterns and keep you updated.

**Comment by brentgunderson** [comment] 2019-04-09 19:51
I seem to encounter similar issues. Reinstall did not seem to help. Do you have any additional suggestions?

$ java -version
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.6 (Maipo)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.4.3


> library(RJDBC)
Loading required package: DBI
Loading required package: rJava

> drv=JDBC("com.teradata.jdbc.TeraDriver", "/opt/pmaqa/Teradata/tdgssconfig.jar:/opt/pmaqa/Teradata/terajdbc4.jar")
Error in .jfindClass(as.character(driverClass)[1]) :
  java.lang.ClassNotFoundException

> print(.jclassPath())
[1] "/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/rJava/java"
[2] "/opt/pmaqa/Teradata/tdgssconfig.jar"
[3] "/opt/pmaqa/Teradata/terajdbc4.jar"
[4] "/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/RJDBC/java/RJDBC.jar"

> file.exists("/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/rJava/java")
[1] TRUE
> file.exists("/opt/pmaqa/Teradata/tdgssconfig.jar")
[1] TRUE
> file.exists("/opt/pmaqa/Teradata/terajdbc4.jar")
[1] TRUE
> file.exists("/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/RJDBC/java/RJDBC.jar")
[1] TRUE

**Comment by s-u** [comment] 2019-04-09 20:26
See  above - enable debugging to tell you in more detail why it's failing. Often it's either JVM version mismatch or lack of dependencies.

**Comment by brentgunderson** [comment] 2019-04-09 21:21
Thanks .... I guess I missed the output of the debugging.  I am struggling a bit to understand it, though I can see that some things are missing, just can't quite understand why. I think I have the right Teradata .jar files (grabbed them from here: https://downloads.teradata.com/download/connectivity/jdbc-driver), and I installed the dependencies for RJDBC. Thanks for the help

```
RJavaClassLoader("/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/rJava","/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/rJava/libs")
 - primary loader
 - registered JRI: /opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/rJava/jri/libjri.so
RJavaClassLoader initialized.

Registered libraries:
  jri: '/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/rJava/jri/libjri.so'
  rJava: '/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/rJava/libs/rJava.so'

Registered class paths:
  '/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/rJava/java'

-- end of class loader report --
RJavaClassLoader: added '/opt/pmaqa/Teradata/tdgssconfig.jar' to the URL class path loader
RJavaClassLoader: adding Java archive file '/opt/pmaqa/Teradata/tdgssconfig.jar' to the internal class path
RJavaClassLoader: added '/opt/pmaqa/Teradata/terajdbc4.jar' to the URL class path loader
RJavaClassLoader: adding Java archive file '/opt/pmaqa/Teradata/terajdbc4.jar' to the internal class path
RJavaClassLoader@5c647e05.findClass(RJavaTools)
 - URL loader did not find it: java.lang.ClassNotFoundException: RJavaTools
RJavaClassLoader.findClass("RJavaTools")
 - trying class path "/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/rJava/java"
   Directory, can get '/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/rJava/java/RJavaTools.class'? YES
  loading class file, initial n = 9829
  next n = -1 (rp=9829, al=131072)
RJavaClassLoader: loaded class RJavaTools, 9829 bytes
  defineClass('RJavaTools') returned class RJavaTools
RJavaClassLoader@5c647e05.findClass(RJavaImport)
 - URL loader did not find it: java.lang.ClassNotFoundException: RJavaImport
RJavaClassLoader.findClass("RJavaImport")
 - trying class path "/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/rJava/java"
   Directory, can get '/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/rJava/java/RJavaImport.class'? YES
  loading class file, initial n = 3468
  next n = -1 (rp=3468, al=131072)
RJavaClassLoader: loaded class RJavaImport, 3468 bytes
  defineClass('RJavaImport') returned class RJavaImport
RJavaClassLoader: added '/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/RJDBC/java/RJDBC.jar' to the URL class path loader
RJavaClassLoader: adding Java archive file '/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/RJDBC/java/RJDBC.jar' to the internal class path
RJavaClassLoader@5c647e05.findClass(com.teradata.jdbc.TeraDriver)
 - URL loader did not find it: java.lang.ClassNotFoundException: com.teradata.jdbc.TeraDriver
RJavaClassLoader.findClass("com.teradata.jdbc.TeraDriver")
 - trying class path "/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/rJava/java"
   Directory, can get '/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/rJava/java/com/teradata/jdbc/TeraDriver.class'? NO
 - trying class path "/opt/pmaqa/Teradata/tdgssconfig.jar"
   JAR file, can get 'com/teradata/jdbc/TeraDriver'? NO
 - trying class path "/opt/pmaqa/Teradata/terajdbc4.jar"
   JAR file, can get 'com/teradata/jdbc/TeraDriver'? NO
 - trying class path "/opt/pmaqa/R/x86_64-redhat-linux-gnu-library/3.4/RJDBC/java/RJDBC.jar"
   JAR file, can get 'com/teradata/jdbc/TeraDriver'? NO
    >> ClassNotFoundException

**Comment by brentgunderson** [comment] 2019-04-09 21:37
Apologies, user error. Reloaded Teradata drivers, seemed to work.

Followup question...is there any way to call in password from file secured away in someplace like user's home directory? 

thank you

**Closed** 2020-02-28 02:56 UTC
